### PR TITLE
Separate Dhall Option type from Option

### PR DESCRIPTION
**Pull request by AlexMouton**
Hi Kazu

Deriving Dhall types from the internal Option type caused the key prefixes to be exposed in the config files. Also, the Option type as exposed in Dhall was free to drift from the internal representation.   

This change uses the TH approach from the Dhall Routes change so the dhall type drives its haskell representation, and then the mapping between the dhall and internal types can be concrete.  This makes the Dhall versions look a little cleaner too.

Thanks
Alex

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
Sorry for the delay. Should I merge this PR before #21?

**Comment by kazu-yamamoto** [comment]
@AlexMouton Gentle ping

**Comment by AlexMouton** [comment]
Hi Kazu
Sorry for the delay.   This one first please! if you like it
Will have more for the other PR in a little while.

**Comment by kazu-yamamoto** [comment]
Merged. Thank you for your review.

**Pull request merged**
