### PR TITLE
Added dhall as an alternative to custom config format

### PR DESCRIPTION
**Pull request by AlexMouton**
Hi Kazu
I would like to deriving some mighty configs from a broader configuration of services. Instead of generating custom config files again, I thought I would look at integrating Dhall as a fallback.  It looks like it works!  I thought Id share to see if you had any thoughts.

One detail of the change that I switched all Ints in the Option to Dhalls Natural.  The Option parser was already avoiding negative ints but this brings the constraint up to the surface, and matches the intent it seems.

Thanks
Alex Mouton

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
I'm new to dhall but I heard very good reputations. So, I'm quite positive to migrate to dhall based configuration. 

BTW, I cannot build mighty with this PR:

```
src/Server.hs:98:29: error:
    • Couldn't match expected type ‘Int’
                  with actual type ‘GHC.Natural.Natural’
```

**Comment by AlexMouton** [comment]
Oh strange. I will look into it.

**Comment by AlexMouton** [comment]
Ah.  It didnt compile probably because I was just working from the tests. try now.

I'm  looking at doing the same thing for routes.  I see Domain is defined as Bytestring. Is that just for unicode?  Can it be Text instead through the UI?  Theres no provision in dhall for bytestring but their Text is unicode it seems.

**Comment by kazu-yamamoto** [comment]
I have read the code and felt excellent. This PR has been merged. Thank you for your contribution!

If necessary, I will release a new version.

**Comment by kazu-yamamoto** [comment]
I did not answer your question, sorry.
I think that `Domain` should be `Text`.

**Comment by AlexMouton** [comment]
Thanks!  I have routes almost done in the same way.   

Two question for you:

Is it ok to be casting from Natural/Text etc to underlying types repeatedly in WaiApp.hs?  It doesnt seem very optimal but this may not be a hot spot for a mighttpd app?

Have you thought  about unicode domain names? I havnt seen that they were supported so I have added punycode conversion locally which seems to be the way thats done.

**Pull request merged**
